In [2]:
# Import Scraping Modules 

from urllib.request import urlopen
from bs4 import BeautifulSoup

#Import data manipulation and viz packages 

import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import matplotlib as mpl
import statistics

In [3]:
#url page for NFL Passing Leaders for 2020-2021 Season 

url = 'https://www.pro-football-reference.com/years/2020/rushing.htm'

#Use the scraping module to open url and pass to Beautiful Soup

html = urlopen(url)

stats_sheet = BeautifulSoup(html)

In [8]:
#Fetch column header - 1st row; since the chart has two levels: Games & Rushing as 1st row, we will select index 1 for column headers

column_headers = stats_sheet.findAll('tr')[1]

column_headers = [i.getText() for i in column_headers.findAll('th')]

print(column_headers)

table_row = stats_sheet.findAll('tr')[2:]

rush_stats = []

for i in range(len(table_row)):
    rush_stats.append([col.getText() for col in table_row[i].findAll('td')])
    
print(rush_stats[0])

['Rk', 'Player', 'Tm', 'Age', 'Pos', 'G', 'GS', 'Att', 'Yds', 'TD', '1D', 'Lng', 'Y/A', 'Y/G', 'Fmb']
['Derrick Henry *+', 'TEN', '26', 'RB', '16', '16', '378', '2027', '17', '98', '94', '5.4', '126.7', '3']

In [20]:
#We will have our column heads and stats_sheet. Let's create the dataframe

rush_df = pd.DataFrame(rush_stats, columns=column_headers[1:])

#View the head of our new dataframe
rush_df.head()

,Player,Tm,Age,Pos,G,GS,Att,Yds,TD,1D,Lng,Y/A,Y/G,Fmb
0,Derrick Henry *+,TEN,26,RB,16,16,378,2027,17,98,94,5.4,126.7,3
1,Dalvin Cook*,MIN,25,RB,14,14,312,1557,16,91,70,5.0,111.2,5
2,Josh Jacobs*,LVR,22,RB,15,15,273,1065,12,61,28,3.9,71.0,2
3,David Montgomery,CHI,23,RB,15,14,247,1070,8,59,80,4.3,71.3,1
4,Ezekiel Elliott,DAL,25,RB,15,15,244,979,6,62,31,4.0,65.3,6

Games
G -- Games played
<br>
GS -- Games started as an offensive or defensive player
<br>
Rushing
<br>
Att -- Rushing Attempts (sacks not included in NFL)
<br>
Yds -- Rushing Yards Gained (sack yardage is not included by NFL)
<br>
TD -- Rushing Touchdowns
<br>
1D -- First downs rushing
<br>
Lng -- Longest Rushing Attempt
<br>
Y/A -- Rushing Yards per Attempt
Minimum 6.25 rushes per game scheduled to qualify as leader.
Minimum 750 rushes to qualify as career leader.
<br>
Y/G -- Rushing Yards per Game
(minimum half a game per game scheduled to qualify as leader)
(Rushing Yards)/(Games Played)
<br>
Fumbles
Fmb -- Number of times fumbled both lost and recovered by own team

In [38]:
#Select categories for viz and analysis 

# Att, Yds, TD, 1D, Y/A, Fmb

categories = ['Att', 'Yds', 'TD', '1D', 'Y/A', 'Fmb']

final_df = rush_df[['Player', 'Tm', 'Pos'] + categories]

final_df.head()

             Player   Tm Pos    Att     Yds    TD    1D  Y/A  Fmb
0  Derrick Henry *+  TEN  RB  378.0  2027.0  17.0  98.0  5.4  3.0
1      Dalvin Cook*  MIN  RB  312.0  1557.0  16.0  91.0  5.0  5.0
2      Josh Jacobs*  LVR  RB  273.0  1065.0  12.0  61.0  3.9  2.0
3  David Montgomery  CHI  RB  247.0  1070.0   8.0  59.0  4.3  1.0
4   Ezekiel Elliott  DAL  RB  244.0   979.0   6.0  62.0  4.0  6.0

In [39]:
#Check the data types of final subset used for our analysis 
final_df.dtypes

Player     object
Tm         object
Pos        object
Att       float64
Yds       float64
TD        float64
1D        float64
Y/A       float64
Fmb       float64
dtype: object

In [40]:
#We must convert the categories to numerical data since we cannot analyze objects for this project

for i in categories:
    final_df[i] = pd.to_numeric(final_df[i])
    
final_df.dtypes

<ipython-input-40-a8d7fc3dde86>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df[i] = pd.to_numeric(final_df[i])

Player     object
Tm         object
Pos        object
Att       float64
Yds       float64
TD        float64
1D        float64
Y/A       float64
Fmb       float64
dtype: object

In [41]:
final_df['Player'] = final_df['Player'].str.replace('*','')

final_df['Player'] = final_df['Player'].str.replace('+', '')

final_df.head()

<ipython-input-41-6c6fa062fd47>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['Player'] = final_df['Player'].str.replace('*','')
<ipython-input-41-6c6fa062fd47>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['Player'] = final_df['Player'].str.replace('+', '')

             Player   Tm Pos    Att     Yds    TD    1D  Y/A  Fmb
0    Derrick Henry   TEN  RB  378.0  2027.0  17.0  98.0  5.4  3.0
1       Dalvin Cook  MIN  RB  312.0  1557.0  16.0  91.0  5.0  5.0
2       Josh Jacobs  LVR  RB  273.0  1065.0  12.0  61.0  3.9  2.0
3  David Montgomery  CHI  RB  247.0  1070.0   8.0  59.0  4.3  1.0
4   Ezekiel Elliott  DAL  RB  244.0   979.0   6.0  62.0  4.0  6.0

In [43]:
#Filter by at least 400 yards rushed and only running backs (RB)

rush_400 = final_df[final_df['Yds'] > 400]

rush_400[rush_400['Pos'].isin(['RB', 'rb'])]

                   Player   Tm Pos    Att     Yds    TD    1D  Y/A  Fmb
0          Derrick Henry   TEN  RB  378.0  2027.0  17.0  98.0  5.4  3.0
1             Dalvin Cook  MIN  RB  312.0  1557.0  16.0  91.0  5.0  5.0
2             Josh Jacobs  LVR  RB  273.0  1065.0  12.0  61.0  3.9  2.0
3        David Montgomery  CHI  RB  247.0  1070.0   8.0  59.0  4.3  1.0
4         Ezekiel Elliott  DAL  RB  244.0   979.0   6.0  62.0  4.0  6.0
5          James Robinson  JAX  RB  240.0  1070.0   7.0  54.0  4.5  3.0
6            Kenyan Drake  ARI  RB  239.0   955.0  10.0  59.0  4.0  3.0
7         Jonathan Taylor  IND  RB  232.0  1169.0  11.0  69.0  5.0  1.0
8           Melvin Gordon  DEN  RB  215.0   986.0   9.0  46.0  4.6  4.0
9             Aaron Jones  GNB  RB  201.0  1104.0   9.0  52.0  5.5  2.0
10            Kareem Hunt  CLE  rb  198.0   841.0   6.0  44.0  4.2  2.0
11            Todd Gurley  ATL  RB  195.0   678.0   9.0  45.0  3.5  2.0
12        Ronald Jones II  TAM  RB  192.0   978.0   7.0  48.0  5.1  2.0
13             Nick Chubb  CLE  RB  190.0  1067.0  12.0  56.0  5.6  1.0
14             Frank Gore  NYJ  RB  187.0   653.0   2.0  32.0  3.5  1.0
15           Alvin Kamara  NOR  RB  187.0   932.0  16.0  58.0  5.0  1.0
16  Clyde Edwards-Helaire  KAN  RB  181.0   803.0   4.0  39.0  4.4  0.0
17        Antonio Gibson   WAS  RB  170.0   795.0  11.0  40.0  4.7  1.0
18           James Conner  PIT  RB  169.0   721.0   6.0  42.0  4.3  2.0
19             Mike Davis  CAR  RB  165.0   642.0   6.0  38.0  3.9  1.0
20          Miles Sanders  PHI  RB  164.0   867.0   6.0  39.0  5.3  4.0
22        Adrian Peterson  DET  RB  156.0   604.0   7.0  34.0  3.9  0.0
23       Devin Singletary  BUF  RB  156.0   687.0   2.0  40.0  4.4  1.0
24          Wayne Gallman  NYG  RB  147.0   682.0   6.0  35.0  4.6  1.0
25          David Johnson  HOU  RB  147.0   691.0   6.0  38.0  4.7  2.0
26        Latavius Murray  NOR  rb  146.0   656.0   4.0  36.0  4.5  1.0
28            Gus Edwards  BAL  rb  144.0   723.0   6.0  45.0  5.0  1.0
30           Myles Gaskin  MIA  RB  142.0   584.0   3.0  27.0  4.1  2.0
31           Chris Carson  SEA  RB  141.0   681.0   5.0  43.0  4.8  1.0
32      Darrell Henderson  LAR  RB  138.0   624.0   5.0  40.0  4.5  0.0
33          Damien Harris  NWE  RB  137.0   691.0   2.0  30.0  5.0  1.0
38        Giovani Bernard  CIN  RB  124.0   416.0   3.0  23.0  3.4  1.0
39              Joe Mixon  CIN  rb  119.0   428.0   3.0  20.0  3.6  1.0
41        Phillip Lindsay  DEN  rb  118.0   502.0   1.0  19.0  4.3  0.0
42          Austin Ekeler  LAC  RB  116.0   530.0   1.0  26.0  4.6  1.0
47         Raheem Mostert  SFO  RB  104.0   521.0   2.0  22.0  5.0  1.0
69            Sony Michel  NWE  rb   79.0   449.0   1.0  19.0  5.7  0.0